---
version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: "${UID}:${GID}"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "${files_root_path}:/srv"
      - "${db_path}:/database.db"
      - "${json_path}:/.filebrowser.json"
    restart: unless-stopped
networks:
  default:
    external: true
    name: home