---
version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.26.0
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "${files_root_path}:/srv"
      - "${db_path}:/database.db"
      - "${json_path}:/.filebrowser.json"
    restart: unless-stopped
networks:
  default:
    external: true
    name: home