version: '3.8'
services:
  onedev:
    privileged: true
    container_name: onedev
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - onedev:/opt/onedev
    image: 1dev/server:9.2.5
    
networks:
  default:
    external: true
    name: home

volumes:
  onedev:
  