version: '3.8'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.14.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${configs_path}:/app/data/configs"
      - "${icons_path}:/app/public/icons"
      - "${data_path}:/data"
    environment:
      - PUID=1000
      - PGID=1000
networks:
  default:
    external: true
    name: home
