version: '3.8'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.14.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/container/data/homarr/configs:/app/data/configs
      - /srv/container/data/homarr/icons:/app/public/icons
      - /srv/container/data/homarr/data:/data
networks:
  default:
    external: true
    name: home
