---
version: "3.8"
services:
  openobserve:
    container_name: openobserve
    image: openobserve/openobserve:v0.7.0
    restart: unless-stopped
    environment:
      - "ZO_TELEMETRY=false"
      - "ZO_DATA_DIR=/data"
      - "ZO_ROOT_USER_EMAIL=${EMAIL}"
      - "ZO_ROOT_USER_PASSWORD=${PASSWORD}"
    volumes:
      - "${DATA_PATH}=/data"
networks:
  default:
    external: true
    name: home