---
version: "3.8"
services:
  freshrss:
    image: linuxserver/freshrss:1.22.1
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "${config_path}:/config"
    restart: unless-stopped
networks:
  default:
    external: true
    name: home